name: Auto Update Repo Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday

jobs:
  update-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python (Optional)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Ensure Correct Repo Structure
        run: |
          mkdir -p src tests docs
          mv scripts/*.sh tools/ 2>/dev/null || true
          mv README.md docs/ 2>/dev/null || true
          touch src/.gitkeep tests/.gitkeep docs/.gitkeep

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-update repo structure"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
